config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "topics/search" => "topics#search"
  resources :topics 
  post "users/create" => "users#create"
  get "signup" => "users#new" 
  get "login" => "users#login_form"
  get "mytopics" => "topics#mytopics"
  post "login" => "users#login"
  post "logout" => "users#logout"
  post "topics/choice_create" => "choices#create"
  post "topics/votes" => "choices#votes"
  post "topics/votes_cancel" => "choices#votes_cancel"
  post "topics/choice_delete" => "choices#destroy"
  root 'topics#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
    validates :content,presence: true
    validates :votes, presence: true
   
end

app/models/done.rb
class Done < ApplicationRecord
    validates :done_user, presence: true
    validates :done_topic, presence: true
    validates :done, presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
    validates :body,presence: true
    validates :title,presence: true
    validates :user_id,presence: true
    
    def self.search(keyword)
        where(["title like? OR body like?", "%#{keyword}%", "%#{keyword}%"])
    end
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true
    validates :email, {presence: true, uniqueness: true }
    validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
    def create
        # topicの特定
       @topic = Topic.find_by(id: params[:topic_id])
    #   選択肢の作成
       @choice = Choice.new(
        #   選択肢
           content: params[:content],
        #   投票数
           votes: 0,
        #   topicのid
           topic_id: @topic.id)
        #   choiceの保存
       if @choice.save 
           redirect_to topic_path(@topic)
     
       end
    end
    
    def votes
        # 投票する選択肢の特定
        @choice = Choice.find_by(id: params[:choice_id])
        #１増やす
        @choice.votes += 1
        # topicの特定
        @topic = Topic.find_by(id: @choice.topic_id)
         @done = Done.find_by(
            done_user: session[:user_id], 
            done_topic: @topic.id,
            done: 0)
        if @choice.save 
            # && @done.update(choice_id: @choice.id,done:1)
            redirect_to topic_path(@topic)
        end
    end
    def votes_cancel
        # 投票する選択肢の特定
        @choice = Choice.find_by(id: params[:choice_id])
        # topicの特定
        @topic = Topic.find_by(id: @choice.topic_id)
        #１減らす
        if @choice.votes > 0
            @choice.votes -= 1
        end
        # @done = Done.find_by(
            # done_user: session[:user_id],
            # done_topic: @topic.id,
            # choice_id: @choice.id,
            # done: 1)
        
        if @choice.save 
            # && @done.update(done: 0)
            redirect_to topic_path(@topic)
        end
    end
    # 選択肢の削除
    def destroy
        @choice =Choice.find_by(id: params[:choice_id])
        @topic = Topic.find_by(id: @choice.topic_id)
        # @done = Done.where(
        #     done_topic: @topic.id,
        #     choice_id: @choice.id)
        if @choice.destroy 
            # && @done.destroy_all
            redirect_to topic_path(@topic)
        end
    end
    
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    # top画面表示
    def index
        @topics = Topic.all.order(created_at: 'desc')
        if session[:user_id]
            @user = User.find(session[:user_id])
        end
    end
    # 自分の作成した記事一覧詳細
    def mytopics
        @mytopics = Topic.where(user_id: session[:user_id])
        if session[:user_id]
            @user = User.find(session[:user_id])
        end
    end
    # 検索機能
    def search 
          @posts = Topic.search(params[:keyword])
          @keyword = params[:keyword]
        if session[:user_id]
            @user = User.find(session[:user_id])
        end
    end
        
    # 投稿詳細
    def show
        if session[:user_id]
            @user = User.find(session[:user_id])
        end
        @topic = Topic.find(params[:id])
        @choices = Choice.where(topic_id: @topic.id)
        @total = Choice.where(topic_id: @topic.id).sum(:votes)
    end
    # 新規投稿作成
    def new
        @topic = Topic.new
        if session[:user_id]
            @user = User.find(session[:user_id])
        end
       
    end
    def create
        if session[:user_id]
            @user = User.find(session[:user_id])
        end
        # 投稿
        @topic = Topic.new(topic_params)
        # user_idにログインしている人のid
        @topic.user_id = session[:user_id]
        # 保存
        if @topic.save
            redirect_to root_path
        end
    end
    # 編集画面
    def edit
        @topic = Topic.find(params[:id])
        if session[:user_id]
            @user = User.find(session[:user_id])
        end
    end
    # 更新機能
    def update
        if session[:user_id]
            @user = User.find(session[:user_id])
        end
        @topic = Topic.find(params[:id])
         if @topic.update(topic_params)
            redirect_to topic_path(@topic)
         else
            render 'edit'
         end
    end
    
    # 削除機能
    def destroy
        @topic = Topic.find(params[:id])
        @choices = Choice.where(topic_id: @topic.id)
       if @topic.destroy && @choices.destroy_all
        redirect_to topics_path
       end
    end
    # strong parameter
    private 
    def topic_params
        params.require(:topic).permit(:title, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new()
    end
    def create
        @user = User.new(
            name: params[:name],
            email: params[:email],
            password: params[:password])
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path
        else
            render("users/new")
        end
    end
    # ログイン画面へ
    def login_form
        if session[:user_id]
            @user = User.find(session[:user_id])
        end
    end
    # ログイン処理
    def login
        @user = User.find_by(email: params[:email],password: params[:password])
        if @user
            session[:user_id] = @user.id
            redirect_to topics_path
        else
            @error_message = "メールアドレスまたはパスワードが間違っています"
            render("login_form")
        end
    end
    def logout
        session[:user_id] = nil
        redirect_to topics_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Research.com</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
           <ul>
            <li>このサイトについて</li>
            <% if session[:user_id] %>
              <li><%= link_to '新しいTopicを投稿する', new_topic_path ,{class: "link"}%></li>
              <li><%= link_to "ログアウト", logout_path, {method: "post",class: "link"} %></li>
              <li><%= @user.name %></li>
            <% else %>
              <li><%= link_to '新規登録', "/signup" ,{class: "link"} %></li>
              <li><%= link_to 'ログイン', "/login" ,{class: "link"} %></li>
            <% end %>
            </ul>
    </header>
    <%= yield %>
  </body>
</html>

app/views/topics/edit.html.erb
 <h1>Topicの変更</h1>
 <%= form_for @topic, url:topic_path(@topic) do |f|%>
 <h2>タイトルの変更</h2>
        <!--タイトル入力-->
        <%= f.text_field :title,class: "Text" ,placeholder: @topic.title %>
        <!--エラー表示-->
        <% if @topic.errors.messages[:title].any? %>
         <span class="error"><%= @topic.errors.messages[:title][0] %></span>
        <% end %>
    <h2>記事の中身の変更</h2>
        <!--本文入力-->
        <%= f.text_area :body,class: "Text", placeholder: @topic.body %>
        <% if @topic.errors.messages[:body].any? %>
         <span class="error"><%= @topic.errors.messages[:body][0] %></span>
        <% end %>
        <!--投稿ボタン-->
        <%= f.submit  value="変更" ,class: "edit" %>
 <% end %>
 <%= link_to "戻る" ,topic_path , class: "backlink link"%>

app/views/topics/index.html.erb
        <div class="main"><h1>Welcome to Research.com！！</h1></div>
            <h1>記事一覧</h1>
        <section class="top">
                <ul class=topics>
                    <% @topics.each do |topic| %>
                    <li class="topic"><%= link_to topic.title, topic_path(topic)%></li>
                    <% end %>
                </ul>
                <ul class="lists">
                <% if session[:user_id] %>
                    <li class="list"><%= link_to '新規投稿作成', new_topic_path%></li>
                    <li class="list"><%= link_to '自分が投稿した記事を確認する', "/mytopics"%></li>
                <% else %>
                    <li class="list"><%= link_to '新規登録', "/signup" ,class: "alist"%> / <%= link_to 'ログイン', "/login"%></li>
                <% end %>
                </ul>
        </section>
        <h1>記事を検索する</h1>
            <%= form_with url: topics_search_path, method: :get, class: "search", local: true do |f| %>
                <%= f.text_field :keyword, value: @keyword,class: "searchForm"%>
                <%= f.submit "検索", class: "searchBtn" %>
            <% end %>
<footer>
   <p class="contactForm"><a href="/" class="link">お問い合わせフォームはこちら</a></p>
</footer>

app/views/topics/mytopics.html.erb
    <h2>自分で投稿した記事一覧</h2>
    <ul class=topics>
        <% @mytopics.each do |topic| %>
        <li class="topic"><%= link_to topic.title, topic_path(topic),class: "topicLink" %></li>
        <% end %>
    </ul>
   <%= link_to 'Topへ', root_path, class: "link backlink" %>

app/views/topics/new.html.erb
  <h1>新規投稿作成</h1>
  <%= form_for :topic, url:topics_path do |f|%>
   <h2>題名</h2>
     <p>
         <!--タイトル入力-->
         <%= f.text_field :title, class: "Text" %>
         <!--エラー表示-->
         <% if @topic.errors.messages[:title].any? %>
          <span class="error"><%= @topic.errors.messages[:title][0] %></span>
         <% end %>
     </p>
     <h3>本文内容</h3>
     <p>
         <!--本文入力-->
         <%= f.text_area :body,class: "Text"%>
         <% if @topic.errors.messages[:body].any? %>
          <span class="error"><%= @topic.errors.messages[:body][0] %></span>
         <% end %>
     </p>
         <!--投稿ボタン-->
         <%= f.submit  value="投稿", class: "submit"%>
    
  <% end %>
  
   <!--topページへ-->
  <%= link_to "Topへ" , root_path, class: "backlink link" %>

 

app/views/topics/search.html.erb
<h1>検索結果</h1>
     <ul class="topics">
        <% @posts.each do |topic| %>
        <li class="topic"><%= link_to topic.title, topic_path(topic),class: "topicLink" %></li>
        <% end %>
        <%= link_to 'Topへ', root_path, class: "link backlink" %>
    </ul>

app/views/topics/show.html.erb
    <!--題名-->
    <h1 class="topicTitle"><%= @topic.title %></h1>

    <!--投稿の内容-->
    <p class="topicBody"><%= @topic.body%></p>
     <!--投稿者の機能-->
    <div class="editFunction">
        <% if session[:user_id] == @topic.user_id %>    
            <%= link_to '編集', edit_topic_path%>
            <%= link_to '削除', topic_path(@topic), method: :delete, data: { confirm: '記事を削除しますか？' }, class: "delete"%>
        <% end %>
            <%= link_to 'Topへ', root_path, class: "backlink" %>
    </div>
           <p class="total">総投票数　<%= @total %></p>
          <!--選択肢を表示-->
    <% @choices.each do | choice | %>
        <div class="choice_div">
            <p class="choice_content"><%= choice.content %><span><%= choice.votes %></span></p>
              <!--選択肢削除機能-->
               <% if session[:user_id] == @topic.user_id %> 
                        <%= form_with model: @choice, url: {controller: "choices", action: "destroy"} do |delete| %>
                              <%= delete.submit "X" ,data: { confirm: '削除しますか？' }, class: "delete_btn" %>
                              <%= hidden_field_tag :choice_id, choice.id %>
                        <% end %>
                <% end %>
            </div>
            <% if session[:user_id] %>
            <div class="votesFunction">
                                <!--投票機能-->
                <% if @user.id == session[:user_id]  %>
                  <%= form_with model: @choice,  url: {controller: "choices", action: "votes"} do |votes| %>
                      <%= votes.submit "投票", class: "votesBtn" %>
                      <%= hidden_field_tag :choice_id, choice.id %>
                  <% end %>
                <% end %> 
                            <!--取り消し機能-->
                <% if @user.id == session[:user_id]%>
                  <%= form_with model: @choice,  url: {controller: "choices", action: "votes_cancel"} do |votes| %>
                          <%= votes.submit "取り消し", class: "cancelBtn" %>
                          <%= hidden_field_tag :choice_id, choice.id %>
                  <% end %>
                <% end %>
            </div>
        <% end %>
    <% end %>
   
      <% if session[:user_id] %>
       <h2>選択肢の作成</h2>
              <!--選択肢の作成-->
         <%= form_with model: @choice,  class: "choice_form",url: {controller: "choices", action: "create"} do |choice| %>
             <!--送信ボタン-->
             <%= choice.submit "+",class: "submit" %>
             <!--選択肢の文章-->
             <%= choice.text_field :content, class: "Text" %>
             <%= hidden_field_tag :topic_id, @topic.id %>
         <% end %>
    <% end %>
     

app/views/users/login_form.html.erb
        <%= form_tag("/login", class: "Form") do %>
         <h1>ログイン画面</h1>
                <%= @error_message %>
            <p>メールアドレス</p>
            <input name="email"  class="usersForm">
            <p>パスワード</p>
            <input type="password" name="password"  class="usersForm">
            <input type="submit" value="ログイン" class="loginForm">            
            <%= link_to "新規登録がまだの方はこちらへ" , signup_path, class: "btn link" %>
            <%= link_to 'Topへ', root_path, class: "backlink link" %>
        <% end %>
    

app/views/users/new.html.erb
        <%= form_tag("/users/create", class: "Form") do %>
            <h1>新規登録</h1>
            <% @user.errors.full_messages.each do |message| %>
                <li class="error"><%= message %></li>
            <% end %>
                <p>名前</p>
                <input name="name" class="usersForm">
                <p>メールアドレス</p>
                <input name="email" class="usersForm">
                <p>パスワード</p>
                <input name="password" type="password" class="usersForm">
                <input type="submit" value="新規登録" class="btn link">
         <%= link_to("ログイン画面へ","/login", class: "loginForm link")%>
         <%= link_to "Topへ戻る" , root_path, class: "backlink link" %>
        <% end %>